FROM python:3.10-slim
WORKDIR /app

# Install dependencies dasar
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pytest-asyncio


COPY src/ ./src/
COPY tests/ ./tests/ 
COPY examples/ ./examples/